# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: images_service_rpc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'images_service_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import images_service_pb2 as images__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18images_service_rpc.proto\x12\napphosting\x1a\x14images_service.proto2\xd6\x03\n\rImagesService\x12V\n\tTransform\x12\".apphosting.ImagesTransformRequest\x1a#.apphosting.ImagesTransformResponse\"\x00\x12V\n\tComposite\x12\".apphosting.ImagesCompositeRequest\x1a#.apphosting.ImagesCompositeResponse\"\x00\x12V\n\tHistogram\x12\".apphosting.ImagesHistogramRequest\x1a#.apphosting.ImagesHistogramResponse\"\x00\x12Y\n\nGetUrlBase\x12#.apphosting.ImagesGetUrlBaseRequest\x1a$.apphosting.ImagesGetUrlBaseResponse\"\x00\x12\x62\n\rDeleteUrlBase\x12&.apphosting.ImagesDeleteUrlBaseRequest\x1a\'.apphosting.ImagesDeleteUrlBaseResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'images_service_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGESSERVICE']._serialized_start=63
  _globals['_IMAGESSERVICE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
