# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import images_service_pb2 as images__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in images_service_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImagesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transform = channel.unary_unary(
                '/apphosting.ImagesService/Transform',
                request_serializer=images__service__pb2.ImagesTransformRequest.SerializeToString,
                response_deserializer=images__service__pb2.ImagesTransformResponse.FromString,
                _registered_method=True)
        self.Composite = channel.unary_unary(
                '/apphosting.ImagesService/Composite',
                request_serializer=images__service__pb2.ImagesCompositeRequest.SerializeToString,
                response_deserializer=images__service__pb2.ImagesCompositeResponse.FromString,
                _registered_method=True)
        self.Histogram = channel.unary_unary(
                '/apphosting.ImagesService/Histogram',
                request_serializer=images__service__pb2.ImagesHistogramRequest.SerializeToString,
                response_deserializer=images__service__pb2.ImagesHistogramResponse.FromString,
                _registered_method=True)
        self.GetUrlBase = channel.unary_unary(
                '/apphosting.ImagesService/GetUrlBase',
                request_serializer=images__service__pb2.ImagesGetUrlBaseRequest.SerializeToString,
                response_deserializer=images__service__pb2.ImagesGetUrlBaseResponse.FromString,
                _registered_method=True)
        self.DeleteUrlBase = channel.unary_unary(
                '/apphosting.ImagesService/DeleteUrlBase',
                request_serializer=images__service__pb2.ImagesDeleteUrlBaseRequest.SerializeToString,
                response_deserializer=images__service__pb2.ImagesDeleteUrlBaseResponse.FromString,
                _registered_method=True)


class ImagesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transform(self, request, context):
        """Perform transformations on the given image and return the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Composite(self, request, context):
        """Composite images onto a canvas and return the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Histogram(self, request, context):
        """Calculate the histogram of an image and return it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUrlBase(self, request, context):
        """Obtains a URL that can serve the image dynamically at different sizes.
        The URL format will look like the following:

        http://lh3.ggpht.com/SomeEncryptedString

        to serve this image at different sizes just append the size option:

        http://lh3.ggpht.com/SomeEncryptedString=s128 (serves a 128 sized image)

        The allowed thumbnail sizes are any integer in the range [0, 1600].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUrlBase(self, request, context):
        """Delete a URL that was created with GetUrlBase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transform': grpc.unary_unary_rpc_method_handler(
                    servicer.Transform,
                    request_deserializer=images__service__pb2.ImagesTransformRequest.FromString,
                    response_serializer=images__service__pb2.ImagesTransformResponse.SerializeToString,
            ),
            'Composite': grpc.unary_unary_rpc_method_handler(
                    servicer.Composite,
                    request_deserializer=images__service__pb2.ImagesCompositeRequest.FromString,
                    response_serializer=images__service__pb2.ImagesCompositeResponse.SerializeToString,
            ),
            'Histogram': grpc.unary_unary_rpc_method_handler(
                    servicer.Histogram,
                    request_deserializer=images__service__pb2.ImagesHistogramRequest.FromString,
                    response_serializer=images__service__pb2.ImagesHistogramResponse.SerializeToString,
            ),
            'GetUrlBase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUrlBase,
                    request_deserializer=images__service__pb2.ImagesGetUrlBaseRequest.FromString,
                    response_serializer=images__service__pb2.ImagesGetUrlBaseResponse.SerializeToString,
            ),
            'DeleteUrlBase': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUrlBase,
                    request_deserializer=images__service__pb2.ImagesDeleteUrlBaseRequest.FromString,
                    response_serializer=images__service__pb2.ImagesDeleteUrlBaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apphosting.ImagesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apphosting.ImagesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImagesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apphosting.ImagesService/Transform',
            images__service__pb2.ImagesTransformRequest.SerializeToString,
            images__service__pb2.ImagesTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Composite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apphosting.ImagesService/Composite',
            images__service__pb2.ImagesCompositeRequest.SerializeToString,
            images__service__pb2.ImagesCompositeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Histogram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apphosting.ImagesService/Histogram',
            images__service__pb2.ImagesHistogramRequest.SerializeToString,
            images__service__pb2.ImagesHistogramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUrlBase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apphosting.ImagesService/GetUrlBase',
            images__service__pb2.ImagesGetUrlBaseRequest.SerializeToString,
            images__service__pb2.ImagesGetUrlBaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUrlBase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apphosting.ImagesService/DeleteUrlBase',
            images__service__pb2.ImagesDeleteUrlBaseRequest.SerializeToString,
            images__service__pb2.ImagesDeleteUrlBaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
